# Security: Pod Security Standards (modern replacement for PodSecurityPolicy)
apiVersion: v1
kind: Namespace
metadata:
  name: hello-world
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
# Pod Security Policy equivalent using Pod Security Standards
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hello-world-pdb
  namespace: hello-world
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: hello-world
